const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const layers=[['Kick','底鼓'],['Snare','军鼓'],['Hi-hat','踩镲'],['Bass','贝斯'],['Melody','旋律']];
const genres=[{name:'HIPHOP',bpm:92,swing:.13,k:[0,6,8,11],s:[4,12],h:[0,2,4,6,8,10,12,14],b:[0,3,8,11],m:[2,7,10,14],notes:[130.81,155.56,174.61,116.54],tip:'Hiphop：先保持 bounce，让重心接住底鼓；军鼓出现时改变动作的质感。'}, {name:'FUNK',bpm:108,swing:.06,k:[0,3,6,10],s:[4,12],h:[0,2,3,4,6,8,10,11,12,14],b:[0,3,6,7,10,14],m:[2,6,10,15],notes:[164.81,196,220,146.83],tip:'Funk：用小幅律动保持 groove，再用短促的停顿回应切分贝斯。'}, {name:'R&B',bpm:76,swing:.2,k:[0,7,10],s:[4,12],h:[0,2,6,8,10,14,15],b:[0,7,10],m:[0,6,12],notes:[146.83,174.61,220,130.81],tip:'R&B：延长身体线条跟随旋律，在军鼓处轻轻收住；不用每一个音都做动作。'}, {name:'HOUSE',bpm:124,swing:0,k:[0,4,8,12],s:[4,12],h:[2,6,10,14],b:[0,6,8,14],m:[2,6,10,14],notes:[130.81,164.81,196,116.54],tip:'House：持续用 jack 呼吸，脚步回应四拍底鼓，再把轻盈感放在反拍踩镲上。'}, {name:'AFRO',bpm:104,swing:.04,k:[0,6,10],s:[4,11,12],h:[0,3,6,8,11,14],b:[0,6,10,14],m:[1,4,7,10,13],notes:[146.83,164.81,220,196],tip:'Afrobeats 练习：让膝盖保持弹性，用躯干和重心回应交错节奏。此循环不代表所有 Afro 音乐。'}];
let genre=0,mode='hunt',ctx,master,muted=false,run=0,timers=[],sources=[],playing=false,phase='idle',missing=0,answered=false,round=0,score=0,streak=0,enabled=[true,true,true,true,true],solo=-1,events=[],used=new Set(),hits=0,extras=0,offsets=[],tapEnd=0;
$('.styles').innerHTML=genres.map((g,i)=>`<button class="style ${i===0?'active':''}" data-genre="${i}"><b>${g.name}</b><small>${g.bpm} BPM</small></button>`).join('');
$('.answers').innerHTML=layers.map((l,i)=>`<button class="answer" data-answer="${i}" disabled><kbd>${i+1}</kbd><b>${l[0]}</b><small>${l[1]}</small></button>`).join('');
$('#mixer').innerHTML=layers.map((l,i)=>`<div class="mix-row"><span>${l[0]} <small>${l[1]}</small></span><button data-enable="${i}" class="active" aria-pressed="true">开</button><button data-solo="${i}" aria-pressed="false">独听</button></div>`).join('');
$('.bars').innerHTML=Array.from({length:57},(_,i)=>`<i style="--h:${16+((i*37)%76)}px;--d:${i*.037}s"></i>`).join('');$('.beats').innerHTML='<i></i>'.repeat(8);
function later(fn,ms){const id=run;timers.push(setTimeout(()=>{if(id===run)fn()},Math.max(0,ms)))}
async function audio(){ctx ||= new (window.AudioContext||window.webkitAudioContext)();if(!master){master=ctx.createGain();master.gain.value=muted?0:.65;master.connect(ctx.destination)}await ctx.resume()}
function stop(){run++;timers.forEach(clearTimeout);timers=[];sources.forEach(s=>{try{s.stop()}catch{}});sources=[];playing=false;$('.stage').classList.remove('playing');$$('.beats i').forEach(b=>b.classList.remove('lit'));$('#lab-play').textContent='▶ 播放 / 暂停实验室'}
function sound(layer,t,step,bar){const g=genres[genre],amp=ctx.createGain();amp.connect(master);let src;
 if(layer===0){src=ctx.createOscillator();src.frequency.setValueAtTime(140,t);src.frequency.exponentialRampToValueAtTime(43,t+.14);amp.gain.setValueAtTime(.65,t);amp.gain.exponentialRampToValueAtTime(.001,t+.27);src.connect(amp);src.start(t);src.stop(t+.29)}
 else if(layer===1||layer===2){const duration=layer===1?.16:.055,buf=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;src=ctx.createBufferSource();src.buffer=buf;const filter=ctx.createBiquadFilter();filter.type='highpass';filter.frequency.value=layer===1?1200:6500;src.connect(filter);filter.connect(amp);amp.gain.setValueAtTime(layer===1?.31:.13,t);amp.gain.exponentialRampToValueAtTime(.001,t+duration);src.start(t);src.stop(t+duration)}
 else{src=ctx.createOscillator();src.type=layer===3?'triangle':'sine';const n=g.notes[(Math.floor(step/4)+bar)%4]*(layer===3?.5:2);src.frequency.setValueAtTime(n,t);src.connect(amp);amp.gain.setValueAtTime(.001,t);amp.gain.linearRampToValueAtTime(layer===3?.38:.17,t+.008);amp.gain.exponentialRampToValueAtTime(.001,t+(layer===3?.22:.38));src.start(t);src.stop(t+.4)}sources.push(src);src.onended=()=>{amp.disconnect();const i=sources.indexOf(src);if(i>=0)sources.splice(i,1)} }
function loop(start,bars,omit=-1,lab=false,collect=false){const g=genres[genre],dt=60/g.bpm/4;for(let bar=0;bar<bars;bar++){['k','s','h','b','m'].forEach((key,l)=>{if(l===omit||lab&&(!enabled[l]||solo!==-1&&solo!==l))return;g[key].forEach(step=>{const t=start+(bar*16+step+(step%2?g.swing:0))*dt;sound(l,t,step,bar);if(collect&&l===0)events.push(t)})});for(let beat=0;beat<4;beat++){later(()=>{$$('.beats i').forEach((b,i)=>b.classList.toggle('lit',i===(bar*4+beat)%8))},(start+(bar*4+beat)*dt*4-ctx.currentTime)*1000)}}return start+bars*16*dt}
function visual(label){playing=true;$('.stage').classList.add('playing');$('#disc-label').innerHTML=label}
function stats(){ $('#score').textContent=score;$('#streak').textContent=streak;$('#progress').textContent=`${round}/5`;$('#progress-bar').style.width=`${round/5*100}%`}
function reset(){stop();phase='idle';round=0;score=0;streak=0;stats();$('#replay').disabled=true;$$('.answer').forEach(b=>{b.disabled=true;b.classList.remove('correct','wrong')});$('#mixer').inert=false;$('#lab-play').disabled=false;$('#start').disabled=false;$('#start').textContent=mode==='hunt'?'▶ 开始听辨':mode==='tap'?'▶ 开始捕捉':'▶ 开始 freestyle';$('#status').textContent=mode==='hunt'?'每轮 2 小节 · 共 5 题 · 不赶时间':mode==='tap'?'先数 4 拍，再跟 Kick 敲击 4 小节。':'4 个八拍的自由练习，不评分。';$('#disc-label').innerHTML='LISTEN<br><b>深听一下</b>'}
function setGenre(i){genre=i;reset();$$('[data-genre]').forEach((b,j)=>b.classList.toggle('active',j===i));$('#tempo').textContent=genres[i].bpm+' BPM';$('#style-tip').textContent=genres[i].tip}
function setMode(m){mode=m;reset();$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#answer-area').hidden=m!=='hunt';$('#tap-area').hidden=m!=='tap';$('#free-area').hidden=m!=='free';$('#session-label').textContent={hunt:'01 / LAYER HUNT',tap:'02 / GROOVE CATCHER',free:'03 / BODY TAKEOVER'}[m];$('#task-title').textContent={hunt:'这个 groove，少了谁？',tap:'用手指，接住底鼓。',free:'把你听见的，跳出来。'}[m];$('#task-desc').textContent={hunt:'先听完整循环，再听缺少一个声部的版本。',tap:'跟着低沉的 Kick 敲击，保持自己的 groove。',free:'跟随身体任务，用一个动作探索不同音乐层次。'}[m]}
async function begin(replay=false){try{await audio()}catch{$('#status').textContent='音频未能启动，请再次点击播放。';return}stop();$('#mixer').inert=true;$('#lab-play').disabled=true;$('#start').disabled=true;$('#replay').disabled=true;
 if(mode==='hunt'){phase='listening';if(!replay){if(round===5){round=0;score=0;streak=0;stats()}missing=Math.floor(Math.random()*5)}answered=false;$$('.answer').forEach(b=>{b.disabled=true;b.classList.remove('correct','wrong')});visual('FULL MIX<br><b>完整版本</b>');$('#status').textContent='先听完整循环，记住每一层声音。';let end=loop(ctx.currentTime+.12,2);later(()=>{visual('MISSING<br><b>谁消失了？</b>');$('#status').textContent='现在少了一层。听完后选择答案。'},(end-ctx.currentTime)*1000);end=loop(end,2,missing);later(()=>{phase='answer';stop();$('#disc-label').innerHTML='YOUR TURN<br><b>做出判断</b>';$$('.answer').forEach(b=>b.disabled=false);$('#replay').disabled=false;$('#status').textContent='哪个声部消失了？按 1—5 或点击作答。'},(end-ctx.currentTime)*1000)}
 else if(mode==='tap'){phase='count';events=[];used.clear();hits=0;extras=0;offsets=[];const beat=60/genres[genre].bpm,start=ctx.currentTime+.15;visual('READY<br><b>准备 4 拍</b>');for(let i=0;i<4;i++){sound(2,start+i*beat,0,0);later(()=>$('#status').textContent=`准备：${4-i}`,(start+i*beat-ctx.currentTime)*1000)}const go=start+4*beat;tapEnd=loop(go,4,-1,false,true);later(()=>{phase='tapping';$('#status').textContent='现在开始！只跟 Kick，每次底鼓敲一下。';visual('CATCH IT<br><b>跟住底鼓</b>')},(go-ctx.currentTime)*1000);later(finishTap,(tapEnd-ctx.currentTime+.25)*1000)}
 else{phase='free';const prompts=['用重心回应底鼓，用肩膀回应军鼓。','脚步保持节拍，上半身只跟贝斯走。','跟旋律延展动作，在军鼓处做一次停顿。','前两个八拍跳得很小，后两个八拍放大同一个动作。'];$('#move-prompt').textContent=prompts[Math.floor(Math.random()*prompts.length)];visual('MOVE<br><b>身体接管</b>');$('#status').textContent='4 个八拍，让身体去选择。';const end=loop(ctx.currentTime+.15,8);later(()=>{stop();phase='idle';$('#start').disabled=false;$('#start').textContent='↻ 换一个身体任务';$('#mixer').inert=false;$('#lab-play').disabled=false;$('#status').textContent='完成！回想：你跟了哪一层？下一轮试着换一层。'},(end-ctx.currentTime)*1000)}}
function answer(i){if(phase!=='answer'||answered)return;answered=true;phase='feedback';round++;const correct=i===missing;if(correct){score+=100;streak++}else streak=0;stats();$$('.answer').forEach((b,j)=>{b.disabled=true;b.classList.toggle('correct',j===missing);b.classList.toggle('wrong',!correct&&j===i)});$('#status').textContent=correct?`听对了！消失的是 ${layers[missing][0]}，+100 分。`:`消失的是 ${layers[missing][0]}（${layers[missing][1]}）。可以在实验室单独听它。`;$('#coach').textContent=round===5?`本轮 ${score/100}/5 答对。${score>=400?'试着把这份听觉带进 freestyle。':'把容易混淆的声部单独听，再来一轮。'}`:['底鼓是低沉的冲击，贝斯带有持续音高。','军鼓更短、更有颗粒感，常形成强烈的拍点。','踩镲是高频的细碎声，能听出节奏的密度。','贝斯有明确的音高变化，连接鼓与旋律。','旋律的音高更突出，可以用动作线条去跟随。'][missing];$('#start').disabled=false;$('#start').textContent=round===5?'↻ 再挑战 5 题':'下一题 →';$('#replay').disabled=true;$('#mixer').inert=false;$('#lab-play').disabled=false}
function tap(){if(phase!=='tapping')return;const t=ctx.currentTime-Number($('#latency').value)/1000;let nearest=-1,d=.16;events.forEach((e,i)=>{if(!used.has(i)&&Math.abs(t-e)<d){d=Math.abs(t-e);nearest=i}});if(nearest>=0){used.add(nearest);hits++;offsets.push(Math.round((t-events[nearest])*1000));$('#status').textContent=d<.065?'正中 groove！':'接住了，继续保持。'}else{extras++;$('#status').textContent='这一拍没有 Kick，继续听低频。'}$('#tap-pad').classList.add('hit');later(()=>$('#tap-pad').classList.remove('hit'),90)}
function finishTap(){stop();phase='idle';const result=Math.max(0,Math.round((hits-extras*.5)/events.length*100));score=result;round=0;stats();$('#progress').textContent=`${hits}/${events.length}`;$('#status').textContent=`本轮 ${result} 分 · 命中 ${hits} · 漏拍 ${events.length-hits} · 多按 ${extras}`;$('#coach').textContent=offsets.length?`平均${offsets.reduce((a,b)=>a+b,0)/offsets.length>=0?'偏晚':'偏早'} ${Math.abs(Math.round(offsets.reduce((a,b)=>a+b,0)/offsets.length))} ms。结果受设备延迟影响，可调补偿后重试。`:'先在实验室独听 Kick，熟悉后再挑战。';$('#start').disabled=false;$('#start').textContent='↻ 再练一轮';$('#lab-play').disabled=false;$('#mixer').inert=false}
async function lab(){if(phase==='lab'){stop();phase='idle';return}if(['listening','answer','count','tapping','free'].includes(phase))return;await audio();stop();phase='lab';visual('EXPLORE<br><b>听清每一层</b>');$('#lab-play').textContent='Ⅱ 暂停实验室';function repeat(){if(phase!=='lab')return;const end=loop(ctx.currentTime+.04,1,-1,true);later(repeat,(end-ctx.currentTime-.02)*1000)}repeat()}
$$('[data-genre]').forEach(b=>b.onclick=()=>setGenre(+b.dataset.genre));$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));$('#start').onclick=()=>begin();$('#replay').onclick=()=>begin(true);$('#lab-play').onclick=lab;$('#tap-pad').onpointerdown=e=>{e.preventDefault();tap()};$('#sound').onclick=()=>{muted=!muted;if(master)master.gain.value=muted?0:.65;$('#sound').textContent='声音 '+(muted?'OFF':'ON')};$('#latency').oninput=()=>$('#latency-value').textContent=$('#latency').value+' ms';
$$('[data-enable]').forEach(b=>b.onclick=()=>{const i=+b.dataset.enable;enabled[i]=!enabled[i];b.classList.toggle('active',enabled[i]);b.setAttribute('aria-pressed',enabled[i]);b.textContent=enabled[i]?'开':'关';refreshLab()});$$('[data-solo]').forEach(b=>b.onclick=()=>{solo=solo===+b.dataset.solo?-1:+b.dataset.solo;$$('[data-solo]').forEach(x=>{const on=+x.dataset.solo===solo;x.classList.toggle('active',on);x.setAttribute('aria-pressed',on)});refreshLab()});function refreshLab(){if(phase==='lab'){stop();phase='idle';lab()}}
document.addEventListener('keydown',e=>{if(e.repeat||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.code==='Space'&&mode==='tap'){e.preventDefault();tap()}else if(/^[1-5]$/.test(e.key)&&mode==='hunt')answer(+e.key-1)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){reset();$('#status').textContent='练习已暂停。回到页面后可重新开始。'}});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'configure_practice',description:'选择音乐风格与训练模式，不启动音频。',inputSchema:{type:'object',properties:{genre:{type:'string',enum:genres.map(g=>g.name)},mode:{type:'string',enum:['hunt','tap','free']}},required:['genre','mode'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const i=genres.findIndex(g=>g.name===input.genre);if(i<0||!['hunt','tap','free'].includes(input.mode))throw Error('无效的风格或模式');setGenre(i);setMode(input.mode);return{genre:genres[i].name,mode,ready:true}}})}catch{}}
