const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const layers=[['Kick','底鼓'],['Snare','军鼓'],['Hi-hat','踩镲'],['Bass','贝斯'],['Melody','旋律']];
// Each profile names a focused substyle. The synthesized tracks are original exercises, not genre-wide templates.
const genres=[
 {name:'HIPHOP',sub:'BOOM BAP',bpm:92,swing:.16,k:[[0,7,10],[0,6,10,15],[0,7,8,11],[0,6,10]],s:[[4,12],[4,12],[4,12],[4,12,15]],h:[[0,2,4,6,8,10,12,14],[0,2,4,6,8,10,12,14,15]],b:[[0,7,10],[0,6,10,15],[0,7,8,11],[0,6,10]],m:[[0,6,10],[2,8,14],[0,7,12],[2,10,14]],roots:[45,41,48,43],tip:'Boom bap：松弛的切分底鼓、2 与 4 拍的军鼓、带摆动的踩镲。用 bounce 接住低频。'},
 {name:'FUNK',sub:'SYNCOPATED FUNK',bpm:106,swing:.025,k:[[0,3,6,10,14],[0,6,9,12,15],[0,3,7,10,14],[0,6,9,13]],s:[[4,12],[4,12,15],[4,12],[4,12]],h:[[0,2,3,4,6,8,10,11,12,14],[0,2,4,5,6,8,10,12,14,15]],b:[[0,3,6,7,10,14],[0,2,6,9,12,15],[0,3,7,10,14],[0,6,9,13,15]],m:[[2,7,10,15],[3,6,11,14],[2,7,10,15],[3,6,12,15]],roots:[40,45,43,47],tip:'Funk：16 分音符切分、短促的贝斯和紧实的军鼓。身体可用停顿与快速反弹回应贝斯。'},
 {name:'R&B',sub:'SLOW JAM',bpm:76,swing:.12,k:[[0,7,10],[0,6,11],[0,7,10],[0,6,10,15]],s:[[4,12],[4,12],[4,12],[4,12]],h:[[0,2,6,8,10,14],[0,2,4,6,8,10,14,15]],b:[[0,7,10],[0,6,11],[0,7,10],[0,6,10,15]],m:[[0,8],[2,10],[0,7,12],[2,8,14]],roots:[45,41,38,40],tip:'慢速 R&B：留白、柔和反拍与持续和声。动作可以延长，不必追每个细碎音。'},
 {name:'HOUSE',sub:'CLASSIC HOUSE',bpm:124,swing:0,k:[[0,4,8,12]],s:[[4,12]],h:[[2,6,10,14],[2,6,10,14,15]],b:[[0,6,8,14],[0,6,8,11,14]],m:[[0,8],[0,6,12],[0,8],[0,6,10,14]],roots:[45,41,38,43],tip:'Classic house：四拍底鼓、反拍开镲、2 与 4 拍 clap。脚步持续，躯干回应反拍。'},
 {name:'AFROBEATS',sub:'AFROBEATS POP',bpm:104,swing:.015,k:[[0,6,10,14],[0,7,10,13],[0,6,11,14],[0,7,10,15]],s:[[4,11,12],[4,12],[4,11,12],[4,12,15]],h:[[0,3,6,8,11,14],[0,2,5,8,10,13]],b:[[0,6,10,14],[0,7,10,13],[0,6,11,14],[0,7,10,15]],m:[[1,4,7,10,13],[2,5,9,12,15]],roots:[45,43,41,43],tip:'Afrobeats 流行取向：交错的鼓与旋律应答、弹性的低频。这里专指 Afrobeats，不代表所有 Afro 音乐。'}
];
const tracks=[
 [
  {title:'街角回声',bpm:92},
  {title:'夜间列车',bpm:88,roots:[38,43,45,41],k:[[0,7,10],[0,6,11],[0,8,10,15],[0,7,10]],h:[[0,2,4,6,8,10,12,14],[0,2,4,6,8,10,12,14,15]],b:[[0,7,10],[0,6,11],[0,8,10,15],[0,7,10]],m:[[0,8],[2,10,14],[0,6,12],[2,8,14]]},
  {title:'磁带微光',bpm:96,roots:[40,48,43,45],k:[[0,6,10],[0,7,11,15],[0,6,8,11],[0,7,10]],h:[[0,2,4,6,8,10,12,14,15],[0,2,4,6,8,10,12,14]],b:[[0,6,10],[0,7,11,15],[0,6,8,11],[0,7,10]],m:[[2,6,12],[0,8,14],[2,10],[0,7,12]]}
 ],[
  {title:'口袋节拍',bpm:106},
  {title:'铜色转角',bpm:112,roots:[43,40,45,38],k:[[0,3,8,10,14],[0,4,7,10,13],[0,3,6,11,14],[0,4,8,10,15]],h:[[0,2,4,5,6,8,10,12,13,14],[0,2,3,4,6,8,9,10,12,14]],b:[[0,3,8,10,14],[0,4,7,10,13],[0,3,6,11,14],[0,4,8,10,15]],m:[[2,6,11,14],[3,7,10,15],[2,6,12,14],[3,6,11,15]]},
  {title:'弹跳电路',bpm:102,roots:[45,38,43,40],k:[[0,6,9,12,15],[0,3,6,10,13],[0,6,9,12,14],[0,3,7,10,15]],h:[[0,2,3,4,6,8,10,12,14,15],[0,2,4,5,6,8,10,11,12,14]],b:[[0,2,6,9,12,15],[0,3,6,10,13],[0,6,9,12,14],[0,3,7,10,15]],m:[[3,6,10,14],[2,7,11,15],[3,8,10,14],[2,6,12,15]]}
 ],[
  {title:'深夜呼吸',bpm:76},
  {title:'柔光房间',bpm:72,roots:[38,43,41,45],k:[[0,10],[0,7,11],[0,10],[0,6,11]],h:[[0,2,6,8,10,14],[0,2,6,8,10,14,15]],b:[[0,10],[0,7,11],[0,10],[0,6,11]],m:[[0,8],[0,6,12],[2,10],[0,8,14]]},
  {title:'雨后慢行',bpm:80,roots:[40,48,41,43],k:[[0,7,10],[0,6,10,15],[0,7,11],[0,6,10]],h:[[0,2,4,6,8,10,14],[0,2,6,8,10,12,14]],b:[[0,7,10],[0,6,10,15],[0,7,11],[0,6,10]],m:[[0,7,12],[2,8,14],[0,6,10],[2,10,14]]}
 ],[
  {title:'四拍脉冲',bpm:124},
  {title:'午夜地板',bpm:120,roots:[38,43,45,41],k:[[0,4,8,12]],h:[[2,6,10,14,15],[2,6,10,14]],b:[[0,6,9,14],[0,6,8,11,14]],m:[[0,8],[2,10],[0,6,12],[2,8,14]]},
  {title:'日出循环',bpm:126,roots:[43,41,45,38],k:[[0,4,8,12]],h:[[2,6,10,14],[2,6,10,14,15]],b:[[0,6,8,11,14],[0,6,10,14]],m:[[2,10],[0,6,12],[0,8],[2,6,10,14]]}
 ],[
  {title:'海风回声',bpm:104},
  {title:'金色步伐',bpm:100,roots:[41,43,45,38],k:[[0,7,10,14],[0,6,11,14],[0,7,10,13],[0,6,10,15]],h:[[0,3,6,9,11,14],[0,2,5,8,11,13]],b:[[0,7,10,14],[0,6,11,14],[0,7,10,13],[0,6,10,15]],m:[[2,5,9,12,15],[1,4,8,11,14]]},
  {title:'街头日落',bpm:108,roots:[43,45,41,43],k:[[0,6,11,14],[0,7,10,15],[0,6,10,13],[0,7,11,14]],h:[[0,2,5,8,10,13],[0,3,6,8,11,14]],b:[[0,6,11,14],[0,7,10,15],[0,6,10,13],[0,7,11,14]],m:[[1,5,8,12,15],[2,4,7,11,14]]}
 ]
];
const active=()=>({...genres[genre],...tracks[genre][track]});
const MIN_SECONDS=45;
const barsFor=(seconds,bpm)=>Math.ceil(seconds*bpm/240);
const trackSeconds=(bars,bpm)=>Math.round(bars*240/bpm);
let genre=0,track=0,mode='hunt',ctx,master,muted=false,run=0,timers=[],sources=[],playing=false,phase='idle',missing=0,answered=false,round=0,score=0,streak=0,enabled=[true,true,true,true,true],solo=-1,events=[],used=new Set(),hits=0,extras=0,offsets=[],tapEnd=0;
$('.styles').innerHTML=genres.map((g,i)=>`<button class="style ${i===0?'active':''}" data-genre="${i}"><b>${g.name}</b><small>${g.bpm} BPM</small></button>`).join('');
$('.answers').innerHTML=layers.map((l,i)=>`<button class="answer" data-answer="${i}" disabled><kbd>${i+1}</kbd><b>${l[0]}</b><small>${l[1]}</small></button>`).join('');
$('#mixer').innerHTML=layers.map((l,i)=>`<div class="mix-row"><span>${l[0]} <small>${l[1]}</small></span><button data-enable="${i}" class="active" aria-pressed="true">开</button><button data-solo="${i}" aria-pressed="false">独听</button></div>`).join('');
$('.bars').innerHTML=Array.from({length:57},(_,i)=>`<i style="--h:${16+((i*37)%76)}px;--d:${i*.037}s"></i>`).join('');$('.beats').innerHTML='<i></i>'.repeat(8);
function later(fn,ms){const id=run;timers.push(setTimeout(()=>{if(id===run)fn()},Math.max(0,ms)))}
async function audio(){ctx ||= new (window.AudioContext||window.webkitAudioContext)();if(!master){master=ctx.createGain();master.gain.value=muted?0:.65;master.connect(ctx.destination)}await ctx.resume()}
function stop(){run++;timers.forEach(clearTimeout);timers=[];sources.forEach(s=>{try{s.stop()}catch{}});sources=[];playing=false;$('.stage').classList.remove('playing');$$('.beats i').forEach(b=>b.classList.remove('lit'));$('#lab-play').textContent='▶ 播放 / 暂停实验室'}
const hz=midi=>440*2**((midi-69)/12);
function osc(type,freq,t,duration,level,cutoff=0){const o=ctx.createOscillator(),gain=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);gain.gain.setValueAtTime(.001,t);gain.gain.linearRampToValueAtTime(level,t+.012);gain.gain.exponentialRampToValueAtTime(.001,t+duration);if(cutoff){const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=cutoff;o.connect(filter);filter.connect(gain)}else o.connect(gain);gain.connect(master);o.start(t);o.stop(t+duration+.01);sources.push(o);o.onended=()=>{gain.disconnect();const i=sources.indexOf(o);if(i>=0)sources.splice(i,1)};return o}
let noiseBuffer;
function noise(t,duration,level,highpass){if(!noiseBuffer){noiseBuffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*.5),ctx.sampleRate);const d=noiseBuffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1}const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();src.buffer=noiseBuffer;filter.type='highpass';filter.frequency.value=highpass;gain.gain.setValueAtTime(level,t);gain.gain.exponentialRampToValueAtTime(.001,t+duration);src.connect(filter);filter.connect(gain);gain.connect(master);src.start(t);src.stop(t+duration);sources.push(src);src.onended=()=>{gain.disconnect();const i=sources.indexOf(src);if(i>=0)sources.splice(i,1)}}
function sound(layer,t,step,bar){const g=active(),root=g.roots[Math.floor(bar/4)%4],v=bar%4;
 if(layer===0){const dur=genre===0?.37:genre===3?.21:.25,o=osc('sine',genre===0?145:125,t,dur,genre===2?.42:.58);o.frequency.exponentialRampToValueAtTime(genre===0?42:49,t+.14);if(genre===1)noise(t,.035,.04,650)}
 else if(layer===1){noise(t,genre===2?.2:.14,genre===2?.16:.27,genre===3?1700:1150);osc('triangle',genre===1?190:160,t,.085,genre===2?.06:.095);if(genre===3)noise(t,.08,.12,2500)}
 else if(layer===2){const open=genre===3&&step%4===2;noise(t,open?.24:genre===2?.045:.065,genre===3?.1:.075,genre===4?3800:5800);if(genre===4&&step%3===1)osc('triangle',620,t,.075,.045)}
 else if(layer===3){const n=root+([-0,0,7,0,3,5,7,0,0,7,3,0,5,7,0,3][step]);const dur=genre===1?.16:genre===2?.45:genre===0?.31:.28;const type=genre===3?'sawtooth':genre===1?'square':genre===4?'triangle':'sine';osc(type,hz(n),t,dur,genre===1?.16:.22,genre===1?700:genre===3?550:0)}
 else{const major=genre!==1&&[41,43,48].includes(root),chord=genre===1?[0,4,7,10]:genre===2?(major?[0,4,7,11]:[0,3,7,10]):(major?[0,4,7]:[0,3,7]);const duration=genre===2?.78:genre===3?.46:genre===1?.18:.32;const level=genre===2?.045:genre===1?.036:.05;const type=genre===1?'square':genre===4?'sine':genre===3?'sawtooth':'triangle';chord.forEach((interval,j)=>osc(type,hz(root+24+interval+(v%2&&j===0?12:0)),t,duration,level,genre===1?1800:genre===3?1200:0))}}
function pattern(g,key,bar){const variants=g[key];return variants[bar%variants.length]}
function loop(start,bars,omit=-1,lab=false,collect=false){const g=active(),dt=60/g.bpm/4;for(let bar=0;bar<bars;bar++){['k','s','h','b','m'].forEach((key,l)=>{if(l===omit||lab&&(!enabled[l]||solo!==-1&&solo!==l))return;pattern(g,key,bar).forEach(step=>{const t=start+(bar*16+step+(step%2?g.swing:0))*dt;sound(l,t,step,bar);if(collect&&l===0)events.push(t)})});for(let beat=0;beat<4;beat++){later(()=>{$$('.beats i').forEach((b,i)=>b.classList.toggle('lit',i===(bar*4+beat)%8))},(start+(bar*4+beat)*dt*4-ctx.currentTime)*1000)}}return start+bars*16*dt}
function visual(label){playing=true;$('.stage').classList.add('playing');$('#disc-label').innerHTML=label}
function stats(){ $('#score').textContent=score;$('#streak').textContent=streak;$('#progress').textContent=`${round}/5`;$('#progress-bar').style.width=`${round/5*100}%`}
function durationText(){const g=active(),seconds=mode==='hunt'?trackSeconds(barsFor(MIN_SECONDS/2,g.bpm)*2,g.bpm):trackSeconds(barsFor(MIN_SECONDS,g.bpm),g.bpm);return `每段约 ${seconds} 秒`}
function reset(){stop();phase='idle';round=0;score=0;streak=0;stats();$('#replay').disabled=true;$$('.answer').forEach(b=>{b.disabled=true;b.classList.remove('correct','wrong')});$('#mixer').inert=false;$('#lab-play').disabled=false;$('#start').disabled=false;$('#start').textContent=mode==='hunt'?'▶ 开始听辨':mode==='tap'?'▶ 开始捕捉':'▶ 开始 freestyle';$('#status').textContent=mode==='hunt'?`${durationText()} · 共 5 题 · 可重复听`:mode==='tap'?`先数 4 拍，再跟 Kick 敲击 ${durationText()}。`:`${durationText()}的自由练习，不评分。`;$('#disc-label').innerHTML='LISTEN<br><b>深听一下</b>'}
function renderTracks(){const g=active();$('#track-list').innerHTML=tracks[genre].map((item,i)=>{const seconds=trackSeconds(barsFor(MIN_SECONDS,item.bpm),item.bpm);return `<button class="track ${track===i?'active':''}" data-track="${i}" aria-pressed="${track===i}"><span class="track-no">0${i+1}</span><span class="track-copy"><b>${item.title}</b><small>${item.bpm} BPM · ${seconds} 秒</small></span></button>`}).join('');$$('[data-track]').forEach(b=>b.onclick=()=>setTrack(+b.dataset.track));$('#tempo').textContent=`${g.bpm} BPM · ${g.sub}`}
function setTrack(i){track=i;reset();renderTracks()}
function setGenre(i){genre=i;track=0;reset();$$('[data-genre]').forEach((b,j)=>b.classList.toggle('active',j===i));renderTracks();$('#style-tip').textContent=genres[i].tip}
function setMode(m){mode=m;reset();$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('#answer-area').hidden=m!=='hunt';$('#tap-area').hidden=m!=='tap';$('#free-area').hidden=m!=='free';$('#session-label').textContent={hunt:'01 / LAYER HUNT',tap:'02 / GROOVE CATCHER',free:'03 / BODY TAKEOVER'}[m];$('#task-title').textContent={hunt:'这个 groove，少了谁？',tap:'用手指，接住底鼓。',free:'把你听见的，跳出来。'}[m];$('#task-desc').textContent={hunt:'先听完整循环，再听缺少一个声部的版本。',tap:'跟着低沉的 Kick 敲击，保持自己的 groove。',free:'跟随身体任务，用一个动作探索不同音乐层次。'}[m]}
async function begin(replay=false){try{await audio()}catch{$('#status').textContent='音频未能启动，请再次点击播放。';return}stop();$('#mixer').inert=true;$('#lab-play').disabled=true;$('#start').disabled=true;$('#replay').disabled=true;
 if(mode==='hunt'){phase='listening';if(!replay){if(round===5){round=0;score=0;streak=0;stats()}missing=Math.floor(Math.random()*5)}answered=false;$$('.answer').forEach(b=>{b.disabled=true;b.classList.remove('correct','wrong')});visual('FULL MIX<br><b>完整版本</b>');const segmentBars=barsFor(MIN_SECONDS/2,active().bpm);$('#status').textContent=`先听完整的 ${segmentBars} 小节，记住每一层声音。`;let end=loop(ctx.currentTime+.12,segmentBars);later(()=>{visual('MISSING<br><b>谁消失了？</b>');$('#status').textContent=`再听同样的 ${segmentBars} 小节：现在少了一层。`},(end-ctx.currentTime)*1000);end=loop(end,segmentBars,missing);later(()=>{phase='answer';stop();$('#disc-label').innerHTML='YOUR TURN<br><b>做出判断</b>';$$('.answer').forEach(b=>b.disabled=false);$('#replay').disabled=false;$('#status').textContent='哪个声部消失了？按 1—5 或点击作答。'},(end-ctx.currentTime)*1000)}
 else if(mode==='tap'){phase='count';events=[];used.clear();hits=0;extras=0;offsets=[];const beat=60/active().bpm,start=ctx.currentTime+.15;visual('READY<br><b>准备 4 拍</b>');for(let i=0;i<4;i++){sound(2,start+i*beat,0,0);later(()=>$('#status').textContent=`准备：${4-i}`,(start+i*beat-ctx.currentTime)*1000)}const go=start+4*beat;tapEnd=loop(go,barsFor(MIN_SECONDS,active().bpm),-1,false,true);later(()=>{phase='tapping';$('#status').textContent=`现在开始！只跟 Kick，持续 ${durationText()}。`;visual('CATCH IT<br><b>跟住底鼓</b>')},(go-ctx.currentTime)*1000);later(finishTap,(tapEnd-ctx.currentTime+.25)*1000)}
 else{phase='free';const prompts=['用重心回应底鼓，用肩膀回应军鼓。','脚步保持节拍，上半身只跟贝斯走。','跟旋律延展动作，在军鼓处做一次停顿。','前半段跳得很小，后半段放大同一个动作。'];$('#move-prompt').textContent=prompts[Math.floor(Math.random()*prompts.length)];visual('MOVE<br><b>身体接管</b>');$('#status').textContent=`${durationText()}，让身体去选择。`;const end=loop(ctx.currentTime+.15,barsFor(MIN_SECONDS,active().bpm));later(()=>{stop();phase='idle';$('#start').disabled=false;$('#start').textContent='↻ 换一个身体任务';$('#mixer').inert=false;$('#lab-play').disabled=false;$('#status').textContent='完成！回想：你跟了哪一层？下一轮试着换一层。'},(end-ctx.currentTime)*1000)}}
function answer(i){if(phase!=='answer'||answered)return;answered=true;phase='feedback';round++;const correct=i===missing;if(correct){score+=100;streak++}else streak=0;stats();$$('.answer').forEach((b,j)=>{b.disabled=true;b.classList.toggle('correct',j===missing);b.classList.toggle('wrong',!correct&&j===i)});$('#status').textContent=correct?`听对了！消失的是 ${layers[missing][0]}，+100 分。`:`消失的是 ${layers[missing][0]}（${layers[missing][1]}）。可以在实验室单独听它。`;$('#coach').textContent=round===5?`本轮 ${score/100}/5 答对。${score>=400?'试着把这份听觉带进 freestyle。':'把容易混淆的声部单独听，再来一轮。'}`:['底鼓是低沉的冲击，贝斯带有持续音高。','军鼓更短、更有颗粒感，常形成强烈的拍点。','踩镲是高频的细碎声，能听出节奏的密度。','贝斯有明确的音高变化，连接鼓与旋律。','旋律的音高更突出，可以用动作线条去跟随。'][missing];$('#start').disabled=false;$('#start').textContent=round===5?'↻ 再挑战 5 题':'下一题 →';$('#replay').disabled=true;$('#mixer').inert=false;$('#lab-play').disabled=false}
function tap(){if(phase!=='tapping')return;const t=ctx.currentTime-Number($('#latency').value)/1000;let nearest=-1,d=.16;events.forEach((e,i)=>{if(!used.has(i)&&Math.abs(t-e)<d){d=Math.abs(t-e);nearest=i}});if(nearest>=0){used.add(nearest);hits++;offsets.push(Math.round((t-events[nearest])*1000));$('#status').textContent=d<.065?'正中 groove！':'接住了，继续保持。'}else{extras++;$('#status').textContent='这一拍没有 Kick，继续听低频。'}$('#tap-pad').classList.add('hit');later(()=>$('#tap-pad').classList.remove('hit'),90)}
function finishTap(){stop();phase='idle';const result=Math.max(0,Math.round((hits-extras*.5)/events.length*100));score=result;round=0;stats();$('#progress').textContent=`${hits}/${events.length}`;$('#status').textContent=`本轮 ${result} 分 · 命中 ${hits} · 漏拍 ${events.length-hits} · 多按 ${extras}`;$('#coach').textContent=offsets.length?`平均${offsets.reduce((a,b)=>a+b,0)/offsets.length>=0?'偏晚':'偏早'} ${Math.abs(Math.round(offsets.reduce((a,b)=>a+b,0)/offsets.length))} ms。结果受设备延迟影响，可调补偿后重试。`:'先在实验室独听 Kick，熟悉后再挑战。';$('#start').disabled=false;$('#start').textContent='↻ 再练一轮';$('#lab-play').disabled=false;$('#mixer').inert=false}
async function lab(){if(phase==='lab'){stop();phase='idle';return}if(['listening','answer','count','tapping','free'].includes(phase))return;await audio();stop();phase='lab';visual('EXPLORE<br><b>听清每一层</b>');$('#lab-play').textContent='Ⅱ 暂停实验室';const end=loop(ctx.currentTime+.04,barsFor(MIN_SECONDS,active().bpm),-1,true);$('#status').textContent=`声部实验室播放 ${durationText()}。`;later(()=>{stop();phase='idle';$('#status').textContent='这段已播完，可调整声部后再次播放。'},(end-ctx.currentTime)*1000)}
$$('[data-genre]').forEach(b=>b.onclick=()=>setGenre(+b.dataset.genre));$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));$('#start').onclick=()=>begin();$('#replay').onclick=()=>begin(true);$('#lab-play').onclick=lab;$('#tap-pad').onpointerdown=e=>{e.preventDefault();tap()};$('#sound').onclick=()=>{muted=!muted;if(master)master.gain.value=muted?0:.65;$('#sound').textContent='声音 '+(muted?'OFF':'ON')};$('#latency').oninput=()=>$('#latency-value').textContent=$('#latency').value+' ms';
$$('[data-enable]').forEach(b=>b.onclick=()=>{const i=+b.dataset.enable;enabled[i]=!enabled[i];b.classList.toggle('active',enabled[i]);b.setAttribute('aria-pressed',enabled[i]);b.textContent=enabled[i]?'开':'关';refreshLab()});$$('[data-solo]').forEach(b=>b.onclick=()=>{solo=solo===+b.dataset.solo?-1:+b.dataset.solo;$$('[data-solo]').forEach(x=>{const on=+x.dataset.solo===solo;x.classList.toggle('active',on);x.setAttribute('aria-pressed',on)});refreshLab()});function refreshLab(){if(phase==='lab'){stop();phase='idle';lab()}}
document.addEventListener('keydown',e=>{if(e.repeat||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.code==='Space'&&mode==='tap'){e.preventDefault();tap()}else if(/^[1-5]$/.test(e.key)&&mode==='hunt')answer(+e.key-1)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){reset();$('#status').textContent='练习已暂停。回到页面后可重新开始。'}});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'configure_practice',description:'选择音乐风格、曲目与训练模式，不启动音频。',inputSchema:{type:'object',properties:{genre:{type:'string',enum:genres.map(g=>g.name)},track:{type:'integer',minimum:1,maximum:3},mode:{type:'string',enum:['hunt','tap','free']}},required:['genre','track','mode'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const i=genres.findIndex(g=>g.name===input.genre);if(i<0||!Number.isInteger(input.track)||input.track<1||input.track>3||!['hunt','tap','free'].includes(input.mode))throw Error('无效的风格、曲目或模式');setGenre(i);setTrack(input.track-1);setMode(input.mode);return{genre:genres[i].name,track:tracks[i][track].title,mode,ready:true}}})}catch{}}
setGenre(0);

